### ISSUE TITLE
Doctor Appointment

### ISSUE THREAD

**Issue by olajidedele** [project-deserve/clinic-alpha-one#3]
### Identity Number

691b1821-5ce4-40e3-a7c4-8cf6c086be09

### Choose a reason for the appointment

Developed an illness
### Select your condition

c-1 - unknown

### Weight

70

### Height

5/6

### Blood Pressure

150

### Select a method of communication

Video Conference

### I acknowledge that submitting this issue does not guarantee an appointment

- [X] Confirm

**Comment by deleolajide** [comment]
Just adding a comment
