### ISSUE TITLE
Schedule an appointment with doctor

### ISSUE THREAD

**Issue by olajidedele** [project-deserve/clinic-alpha-one#63]
### Identity Number

43948300-3832-11ed-9461-3df71b82346f

### Reason for the appointment

Developed a condition

### Medical Condition

c-2 - yyyyyyyyyyyyy

### Medical illness

i-2 - xxxxxxxxxxx

### Weight

52

### Height

5/7

### Blood Pressure

155

### Additional Information

```markdown
Not  sure what the problem is
```

### Method of Communication

Video Conference

### Code of Conduct

- [X] Confirmation

### Expectation

- [X] Confirmation

**Comment by deleolajide** [comment]
Ask patient to come back in two weeks. Thanks
