### ISSUE TITLE
last try

### ISSUE THREAD

**Issue by olajidedele** [project-deserve/clinic-alpha-one#8]
### Identity Number
691b1821-5ce4-40e3-a7c4-8cf6c086be09
### Choose a reason for the appointment
Developed an illness
### Select your condition
c-1 - unknown
### Weight
70
### Height
5/6
### Blood Pressure
150
### Select a method of communication
Video Conference
### I acknowledge that submitting this issue does not guarantee an appointment -
[X] Confirm

**Comment by deleolajide** [comment]
This is a lin - https://github.com/project-deserve/clinic-alpha-one/tree/main/Personal%20Health%20Records/691b1821-5ce4-40e3-a7c4-8cf6c086be09#medications
